### ISSUE TITLE
"DeepRepair is not working, thus it is not selected."

### ISSUE THREAD

**Issue by jose** [SerVal-DTF/APR-Efficiency#2]
Hi @Kui-Liu,

In your paper, [On the Efficiency of Test Suite based Program Repair A Systematic Assessment of 16 Automated Repair Systems for Java Programs](https://dl.acm.org/doi/abs/10.1145/3377811.3380338), the text under Table 2 reports that 

> DeepRepair is not working, thus it is not selected.

Any chance you could provide further details on that?  Why was not DeepRepair working?

Thanks in advance.  Best, Jose

**Comment by Kui-Liu** [comment]
Hello @jose 
DeepRepair is integrated with ASTOR, we always have the problem of "java.lang.NullPointerException at com.gzoltar.core.GZoltar.run" with ASTOR, so we cannot execute DeepRepair. Thus, DeepRepair is not selected.

**Comment by jose** [comment]
Ok, thanks.
